//
// Code generated by go-jet DO NOT EDIT.
// Generated at Saturday, 14-Dec-19 13:49:37 CET
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var Comment = newCommentTable()

type CommentTable struct {
	postgres.Table

	//Columns
	CommentID postgres.ColumnInteger
	UserID    postgres.ColumnInteger
	PictureID postgres.ColumnInteger
	Created   postgres.ColumnTimestamp
	Comment   postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new CommentTable with assigned alias
func (a *CommentTable) AS(alias string) *CommentTable {
	aliasTable := newCommentTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newCommentTable() *CommentTable {
	var (
		CommentIDColumn = postgres.IntegerColumn("comment_id")
		UserIDColumn    = postgres.IntegerColumn("user_id")
		PictureIDColumn = postgres.IntegerColumn("picture_id")
		CreatedColumn   = postgres.TimestampColumn("created")
		CommentColumn   = postgres.StringColumn("comment")
	)

	return &CommentTable{
		Table: postgres.NewTable("image_gallery", "comment", CommentIDColumn, UserIDColumn, PictureIDColumn, CreatedColumn, CommentColumn),

		//Columns
		CommentID: CommentIDColumn,
		UserID:    UserIDColumn,
		PictureID: PictureIDColumn,
		Created:   CreatedColumn,
		Comment:   CommentColumn,

		AllColumns:     postgres.ColumnList{CommentIDColumn, UserIDColumn, PictureIDColumn, CreatedColumn, CommentColumn},
		MutableColumns: postgres.ColumnList{UserIDColumn, PictureIDColumn, CreatedColumn, CommentColumn},
	}
}
