//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 10-Dec-19 10:58:12 CET
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var Customer = newCustomerTable()

type CustomerTable struct {
	postgres.Table

	//Columns
	UserID      postgres.ColumnInteger
	Username    postgres.ColumnString
	FullName    postgres.ColumnString
	Password    postgres.ColumnString
	NumPictures postgres.ColumnInteger
	NumComments postgres.ColumnInteger
	NumLikes    postgres.ColumnInteger
	AvatarID    postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new CustomerTable with assigned alias
func (a *CustomerTable) AS(alias string) *CustomerTable {
	aliasTable := newCustomerTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newCustomerTable() *CustomerTable {
	var (
		UserIDColumn      = postgres.IntegerColumn("user_id")
		UsernameColumn    = postgres.StringColumn("username")
		FullNameColumn    = postgres.StringColumn("full_name")
		PasswordColumn    = postgres.StringColumn("password")
		NumPicturesColumn = postgres.IntegerColumn("num_pictures")
		NumCommentsColumn = postgres.IntegerColumn("num_comments")
		NumLikesColumn    = postgres.IntegerColumn("num_likes")
		AvatarIDColumn    = postgres.IntegerColumn("avatar_id")
	)

	return &CustomerTable{
		Table: postgres.NewTable("image_gallery", "customer", UserIDColumn, UsernameColumn, FullNameColumn, PasswordColumn, NumPicturesColumn, NumCommentsColumn, NumLikesColumn, AvatarIDColumn),

		//Columns
		UserID:      UserIDColumn,
		Username:    UsernameColumn,
		FullName:    FullNameColumn,
		Password:    PasswordColumn,
		NumPictures: NumPicturesColumn,
		NumComments: NumCommentsColumn,
		NumLikes:    NumLikesColumn,
		AvatarID:    AvatarIDColumn,

		AllColumns:     postgres.ColumnList{UserIDColumn, UsernameColumn, FullNameColumn, PasswordColumn, NumPicturesColumn, NumCommentsColumn, NumLikesColumn, AvatarIDColumn},
		MutableColumns: postgres.ColumnList{UsernameColumn, FullNameColumn, PasswordColumn, NumPicturesColumn, NumCommentsColumn, NumLikesColumn, AvatarIDColumn},
	}
}
