//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 10-Dec-19 10:58:12 CET
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var CustomerHasRoles = newCustomerHasRolesTable()

type CustomerHasRolesTable struct {
	postgres.Table

	//Columns
	UserID postgres.ColumnInteger
	Role   postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new CustomerHasRolesTable with assigned alias
func (a *CustomerHasRolesTable) AS(alias string) *CustomerHasRolesTable {
	aliasTable := newCustomerHasRolesTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newCustomerHasRolesTable() *CustomerHasRolesTable {
	var (
		UserIDColumn = postgres.IntegerColumn("user_id")
		RoleColumn   = postgres.StringColumn("role")
	)

	return &CustomerHasRolesTable{
		Table: postgres.NewTable("image_gallery", "customer_has_roles", UserIDColumn, RoleColumn),

		//Columns
		UserID: UserIDColumn,
		Role:   RoleColumn,

		AllColumns:     postgres.ColumnList{UserIDColumn, RoleColumn},
		MutableColumns: postgres.ColumnList{UserIDColumn, RoleColumn},
	}
}
