//
// Code generated by go-jet DO NOT EDIT.
// Generated at Saturday, 14-Dec-19 13:49:37 CET
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var Image = newImageTable()

type ImageTable struct {
	postgres.Table

	//Columns
	ImageID    postgres.ColumnInteger
	UserID     postgres.ColumnInteger
	ThumbURL   postgres.ColumnString
	LowResURL  postgres.ColumnString
	HighResURL postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new ImageTable with assigned alias
func (a *ImageTable) AS(alias string) *ImageTable {
	aliasTable := newImageTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newImageTable() *ImageTable {
	var (
		ImageIDColumn    = postgres.IntegerColumn("image_id")
		UserIDColumn     = postgres.IntegerColumn("user_id")
		ThumbURLColumn   = postgres.StringColumn("thumb_url")
		LowResURLColumn  = postgres.StringColumn("low_res_url")
		HighResURLColumn = postgres.StringColumn("high_res_url")
	)

	return &ImageTable{
		Table: postgres.NewTable("image_gallery", "image", ImageIDColumn, UserIDColumn, ThumbURLColumn, LowResURLColumn, HighResURLColumn),

		//Columns
		ImageID:    ImageIDColumn,
		UserID:     UserIDColumn,
		ThumbURL:   ThumbURLColumn,
		LowResURL:  LowResURLColumn,
		HighResURL: HighResURLColumn,

		AllColumns:     postgres.ColumnList{ImageIDColumn, UserIDColumn, ThumbURLColumn, LowResURLColumn, HighResURLColumn},
		MutableColumns: postgres.ColumnList{UserIDColumn, ThumbURLColumn, LowResURLColumn, HighResURLColumn},
	}
}
