//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 10-Dec-19 10:58:12 CET
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var Like = newLikeTable()

type LikeTable struct {
	postgres.Table

	//Columns
	UserID    postgres.ColumnInteger
	PictureID postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new LikeTable with assigned alias
func (a *LikeTable) AS(alias string) *LikeTable {
	aliasTable := newLikeTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newLikeTable() *LikeTable {
	var (
		UserIDColumn    = postgres.IntegerColumn("user_id")
		PictureIDColumn = postgres.IntegerColumn("picture_id")
	)

	return &LikeTable{
		Table: postgres.NewTable("image_gallery", "like", UserIDColumn, PictureIDColumn),

		//Columns
		UserID:    UserIDColumn,
		PictureID: PictureIDColumn,

		AllColumns:     postgres.ColumnList{UserIDColumn, PictureIDColumn},
		MutableColumns: postgres.ColumnList{UserIDColumn, PictureIDColumn},
	}
}
