//
// Code generated by go-jet DO NOT EDIT.
// Generated at Thursday, 12-Dec-19 11:57:22 CET
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var Picture = newPictureTable()

type PictureTable struct {
	postgres.Table

	//Columns
	PictureID   postgres.ColumnInteger
	UserID      postgres.ColumnInteger
	ImageID     postgres.ColumnInteger
	Title       postgres.ColumnString
	Description postgres.ColumnString
	Created     postgres.ColumnTimestamp
	NumLikes    postgres.ColumnInteger
	NumComments postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new PictureTable with assigned alias
func (a *PictureTable) AS(alias string) *PictureTable {
	aliasTable := newPictureTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newPictureTable() *PictureTable {
	var (
		PictureIDColumn   = postgres.IntegerColumn("picture_id")
		UserIDColumn      = postgres.IntegerColumn("user_id")
		ImageIDColumn     = postgres.IntegerColumn("image_id")
		TitleColumn       = postgres.StringColumn("title")
		DescriptionColumn = postgres.StringColumn("description")
		CreatedColumn     = postgres.TimestampColumn("created")
		NumLikesColumn    = postgres.IntegerColumn("num_likes")
		NumCommentsColumn = postgres.IntegerColumn("num_comments")
	)

	return &PictureTable{
		Table: postgres.NewTable("image_gallery", "picture", PictureIDColumn, UserIDColumn, ImageIDColumn, TitleColumn, DescriptionColumn, CreatedColumn, NumLikesColumn, NumCommentsColumn),

		//Columns
		PictureID:   PictureIDColumn,
		UserID:      UserIDColumn,
		ImageID:     ImageIDColumn,
		Title:       TitleColumn,
		Description: DescriptionColumn,
		Created:     CreatedColumn,
		NumLikes:    NumLikesColumn,
		NumComments: NumCommentsColumn,

		AllColumns:     postgres.ColumnList{PictureIDColumn, UserIDColumn, ImageIDColumn, TitleColumn, DescriptionColumn, CreatedColumn, NumLikesColumn, NumCommentsColumn},
		MutableColumns: postgres.ColumnList{UserIDColumn, ImageIDColumn, TitleColumn, DescriptionColumn, CreatedColumn, NumLikesColumn, NumCommentsColumn},
	}
}
