//
// Code generated by go-jet DO NOT EDIT.
// Generated at Saturday, 14-Dec-19 13:49:37 CET
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var UserHasRoles = newUserHasRolesTable()

type UserHasRolesTable struct {
	postgres.Table

	//Columns
	UserID postgres.ColumnInteger
	Role   postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new UserHasRolesTable with assigned alias
func (a *UserHasRolesTable) AS(alias string) *UserHasRolesTable {
	aliasTable := newUserHasRolesTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newUserHasRolesTable() *UserHasRolesTable {
	var (
		UserIDColumn = postgres.IntegerColumn("user_id")
		RoleColumn   = postgres.StringColumn("role")
	)

	return &UserHasRolesTable{
		Table: postgres.NewTable("image_gallery", "user_has_roles", UserIDColumn, RoleColumn),

		//Columns
		UserID: UserIDColumn,
		Role:   RoleColumn,

		AllColumns:     postgres.ColumnList{UserIDColumn, RoleColumn},
		MutableColumns: postgres.ColumnList{UserIDColumn, RoleColumn},
	}
}
