//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 10-Dec-19 10:58:12 CET
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Customer struct {
	UserID      int32 `sql:"primary_key"`
	Username    string
	FullName    string
	Password    string
	NumPictures int32
	NumComments int32
	NumLikes    int32
	AvatarID    *int32
}
