//
// Code generated by go-jet DO NOT EDIT.
// Generated at Thursday, 12-Dec-19 11:57:22 CET
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Image struct {
	ImageID    int32 `sql:"primary_key"`
	UserID     int32
	ThumbURL   string
	LowResURL  string
	HighResURL string
}
