//
// Code generated by go-jet DO NOT EDIT.
// Generated at Thursday, 12-Dec-19 11:57:22 CET
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Like struct {
	UserID    int32
	PictureID int32
}
