//
// Code generated by go-jet DO NOT EDIT.
// Generated at Saturday, 14-Dec-19 13:49:37 CET
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type User struct {
	UserID      int32 `sql:"primary_key"`
	Username    string
	FullName    string
	Password    string
	NumPictures int32
	NumComments int32
	NumLikes    int32
	AvatarID    *int32
}
